# Generated by Django 3.1.7 on 2021-03-13 20:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Systems Neuroscience', 'Systems Neuroscience'), ('Motor Neuroscience', 'Motor Neuroscience'), ('Molecular Neuroscience', 'Molecular Neuroscience'), ('Behavioural Neuroscience', 'Behavioural Neuroscience'), ('Psychology', 'Psychology'), ('Psychophysics', 'Psychophysics'), ('Cognitive Science', 'Cognitive Science')], max_length=100)),
                ('url_ref', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Tweeprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.URLField()),
                ('score', models.IntegerField(default=0)),
                ('url_ref', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'db_table': 'tweeprints',
                'ordering': ['-date_added'],
            },
        ),
    ]
