# Generated by Django 3.1.7 on 2021-03-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210314_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweeprint',
            name='category',
            field=models.CharField(choices=[('Systems Neuroscience', 'Systems Neuroscience'), ('Motor Neuroscience', 'Motor Neuroscience'), ('Molecular Neuroscience', 'Molecular Neuroscience'), ('Behavioural Neuroscience', 'Behavioural Neuroscience'), ('Psychology', 'Psychology'), ('Psychophysics', 'Psychophysics'), ('Cognitive Science', 'Cognitive Science')], max_length=300),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
