# Generated by Django 3.1.7 on 2021-03-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210314_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweeprint',
            name='tweet_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
