# Generated by Django 3.1.7 on 2021-03-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tweeprint_tweet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweeprint',
            name='name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
