# Generated by Django 3.1.7 on 2021-03-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210314_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweeprint',
            name='category',
            field=models.CharField(choices=[('Systems Neuroscience', 'Systems Neuroscience'), ('Motor Neuroscience', 'Motor Neuroscience'), ('Molecular Neuroscience', 'Molecular Neuroscience'), ('Behavioural Neuroscience', 'Behavioural Neuroscience'), ('Psychology', 'Psychology'), ('Psychophysics', 'Psychophysics'), ('Cognitive Science', 'Cognitive Science'), ('Animal Behavior and Cognition', 'Animal Behavior and Cognition'), ('Biochemistry', 'Biochemistry'), ('Bioengineering', 'Bioengineering'), ('Bioinformatics', 'Bioinformatics'), ('Biophysics', 'Biophysics'), ('Cancer Biology', 'Cancer Biology'), ('Cell Biology', 'Cell Biology'), ('Developmental Biology', 'Developmental Biology'), ('Ecology', 'Ecology'), ('Evolutionary Biology', 'Evolutionary Biology'), ('Genetics', 'Genetics'), ('Genomics', 'Genomics'), ('Immunology', 'Immunology'), ('Microbiology', 'Microbiology'), ('Molecular Biology', 'Molecular Biology'), ('Neuroscience', 'Neuroscience'), ('Paleontology', 'Paleontology'), ('Pathology', 'Pathology'), ('Pharmacology and Toxicology', 'Pharmacology and Toxicology'), ('Physiology', 'Physiology'), ('Plant Biology', 'Plant Biology'), ('Scientific Communication and Education', 'Scientific Communication and Education'), ('Synthetic Biology', 'Synthetic Biology'), ('Systems Biology', 'Systems Biology'), ('Zoology', 'Zoology')], max_length=300),
        ),
    ]
