# Generated by Django 3.1.7 on 2021-03-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210314_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweeprint',
            name='category',
            field=models.CharField(choices=[('Animal Behavior and Cognition', 'Animal Behavior and Cognition'), ('Behavioural Neuroscience', 'Behavioural Neuroscience'), ('Biochemistry', 'Biochemistry'), ('Bioengineering', 'Bioengineering'), ('Bioinformatics', 'Bioinformatics'), ('Biophysics', 'Biophysics'), ('Cancer Biology', 'Cancer Biology'), ('Cell Biology', 'Cell Biology'), ('Cognitive Science', 'Cognitive Science'), ('Developmental Biology', 'Developmental Biology'), ('Ecology', 'Ecology'), ('Evolutionary Biology', 'Evolutionary Biology'), ('Genetics', 'Genetics'), ('Genomics', 'Genomics'), ('Immunology', 'Immunology'), ('Microbiology', 'Microbiology'), ('Molecular Biology', 'Molecular Biology'), ('Molecular Neuroscience', 'Molecular Neuroscience'), ('Motor Neuroscience', 'Motor Neuroscience'), ('Neuroscience', 'Neuroscience'), ('Paleontology', 'Paleontology'), ('Pathology', 'Pathology'), ('Pharmacology and Toxicology', 'Pharmacology and Toxicology'), ('Physiology', 'Physiology'), ('Plant Biology', 'Plant Biology'), ('Psychology', 'Psychology'), ('Psychophysics', 'Psychophysics'), ('Scientific Communication and Education', 'Scientific Communication and Education'), ('Synthetic Biology', 'Synthetic Biology'), ('Structural Biology', 'Structural Biology'), ('Systems Biology', 'Systems Biology'), ('Systems Neuroscience', 'Systems Neuroscience'), ('Zoology', 'Zoology')], max_length=300),
        ),
    ]
