# Generated by Django 3.1.7 on 2021-03-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210314_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweeprint',
            name='category_slug',
            field=models.SlugField(default='', max_length=300),
        ),
    ]
