# Generated by Django 3.2 on 2021-04-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210320_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweeprint',
            name='tweet_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
