# Generated by Django 3.2 on 2021-04-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210411_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweeprint',
            name='tweet_author_name',
        ),
        migrations.RemoveField(
            model_name='tweeprint',
            name='tweet_author_username',
        ),
        migrations.RemoveField(
            model_name='tweeprint',
            name='tweet_created_at',
        ),
        migrations.AddField(
            model_name='tweeprint',
            name='tweet_json',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
