# Generated by Django 3.2 on 2021-04-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210411_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweeprint',
            name='tweet_json',
            field=models.JSONField(blank=True, max_length=10000, null=True),
        ),
    ]
