# Generated by Django 3.2 on 2021-04-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_tweeprint_tweet_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweeprint',
            name='tweet_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
